name: wrk

on:
  schedule:
    - cron: '0/64 * * * *'
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: build
      run: make
      
    - name: gan
      run: ./wrk -t12 -c100 -d3600s ${{ secrets.URL }}
